name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_URL: ${{ secrets.RENDER_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Deploy to Render
        run: |
          curl -X GET "${{ env.RENDER_URL }}"